/* 
 * Maestro API
 *
 * Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Maestro.Model
{
    /// <summary>
    /// A request body that used for create or update workflow definition
    /// </summary>
    [DataContract]
    public partial class CreateOrUpdateWorkflowDefinitionRequestBody :  IEquatable<CreateOrUpdateWorkflowDefinitionRequestBody>, IValidatableObject
    {
        public CreateOrUpdateWorkflowDefinitionRequestBody()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateOrUpdateWorkflowDefinitionRequestBody" /> class.
        /// </summary>
        /// <param name="WorkflowDefinition">WorkflowDefinition.</param>
        public CreateOrUpdateWorkflowDefinitionRequestBody(WorkflowDefinition WorkflowDefinition = default(WorkflowDefinition))
        {
            this.WorkflowDefinition = WorkflowDefinition;
        }
        
        /// <summary>
        /// Gets or Sets WorkflowDefinition
        /// </summary>
        [DataMember(Name="workflowDefinition", EmitDefaultValue=false)]
        public WorkflowDefinition WorkflowDefinition { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateOrUpdateWorkflowDefinitionRequestBody {\n");
            sb.Append("  WorkflowDefinition: ").Append(WorkflowDefinition).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CreateOrUpdateWorkflowDefinitionRequestBody);
        }

        /// <summary>
        /// Returns true if CreateOrUpdateWorkflowDefinitionRequestBody instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateOrUpdateWorkflowDefinitionRequestBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateOrUpdateWorkflowDefinitionRequestBody other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.WorkflowDefinition == other.WorkflowDefinition ||
                    this.WorkflowDefinition != null &&
                    this.WorkflowDefinition.Equals(other.WorkflowDefinition)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.WorkflowDefinition != null)
                    hash = hash * 59 + this.WorkflowDefinition.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
