/* 
 * Maestro API
 *
 * Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Maestro.Model
{
    /// <summary>
    /// DSWebFormsStepConfig
    /// </summary>
    [DataContract]
    public partial class DSWebFormsStepConfig :  IEquatable<DSWebFormsStepConfig>, IValidatableObject
    {
        public DSWebFormsStepConfig()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DSWebFormsStepConfig" /> class.
        /// </summary>
        /// <param name="PageUrl">PageUrl (required).</param>
        public DSWebFormsStepConfig(string PageUrl = default(string))
        {
            // to ensure "PageUrl" is required (not null)
            if (PageUrl == null)
            {
                throw new InvalidDataException("PageUrl is a required property for DSWebFormsStepConfig and cannot be null");
            }
            else
            {
                this.PageUrl = PageUrl;
            }
        }
        
        /// <summary>
        /// Gets or Sets PageUrl
        /// </summary>
        [DataMember(Name="pageUrl", EmitDefaultValue=false)]
        public string PageUrl { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DSWebFormsStepConfig {\n");
            sb.Append("  PageUrl: ").Append(PageUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as DSWebFormsStepConfig);
        }

        /// <summary>
        /// Returns true if DSWebFormsStepConfig instances are equal
        /// </summary>
        /// <param name="other">Instance of DSWebFormsStepConfig to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DSWebFormsStepConfig other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.PageUrl == other.PageUrl ||
                    this.PageUrl != null &&
                    this.PageUrl.Equals(other.PageUrl)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.PageUrl != null)
                    hash = hash * 59 + this.PageUrl.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
