/* 
 * Maestro API
 *
 * Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Maestro.Model
{
    /// <summary>
    /// DSWorkflowBooleanExpression
    /// </summary>
    [DataContract]
    public partial class DSWorkflowBooleanExpression :  IEquatable<DSWorkflowBooleanExpression>, IValidatableObject
    {
        public DSWorkflowBooleanExpression()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Gets or Sets LogicalOperator
        /// </summary>
        [DataMember(Name="logicalOperator", EmitDefaultValue=false)]
        public DSWorkflowLogicalOperatorTypes? LogicalOperator { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DSWorkflowBooleanExpression" /> class.
        /// </summary>
        /// <param name="Expressions">A list of objects. Each object should contain any of the following object models: [#/definitions/DSWorkflowBooleanExpression, #/definitions/DSWorkflowComparisonExpression] (required).</param>
        /// <param name="LogicalOperator">LogicalOperator (required).</param>
        /// <param name="Type">Type (required).</param>
        public DSWorkflowBooleanExpression(List<Object> Expressions = default(List<Object>), DSWorkflowLogicalOperatorTypes? LogicalOperator = default(DSWorkflowLogicalOperatorTypes?), DSWorkflowExpressionTypesBooleanExpression Type = default(DSWorkflowExpressionTypesBooleanExpression))
        {
            // to ensure "Expressions" is required (not null)
            if (Expressions == null)
            {
                throw new InvalidDataException("Expressions is a required property for DSWorkflowBooleanExpression and cannot be null");
            }
            else
            {
                this.Expressions = Expressions;
            }
            // to ensure "LogicalOperator" is required (not null)
            if (LogicalOperator == null)
            {
                throw new InvalidDataException("LogicalOperator is a required property for DSWorkflowBooleanExpression and cannot be null");
            }
            else
            {
                this.LogicalOperator = LogicalOperator;
            }
            // to ensure "Type" is required (not null)
            if (Type == null)
            {
                throw new InvalidDataException("Type is a required property for DSWorkflowBooleanExpression and cannot be null");
            }
            else
            {
                this.Type = Type;
            }
        }
        
        /// <summary>
        /// A list of objects. Each object should contain any of the following object models: [#/definitions/DSWorkflowBooleanExpression, #/definitions/DSWorkflowComparisonExpression]
        /// </summary>
        /// <value>A list of objects. Each object should contain any of the following object models: [#/definitions/DSWorkflowBooleanExpression, #/definitions/DSWorkflowComparisonExpression]</value>
        [DataMember(Name="expressions", EmitDefaultValue=false)]
        public List<Object> Expressions { get; set; }
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public DSWorkflowExpressionTypesBooleanExpression Type { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DSWorkflowBooleanExpression {\n");
            sb.Append("  Expressions: ").Append(Expressions).Append("\n");
            sb.Append("  LogicalOperator: ").Append(LogicalOperator).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as DSWorkflowBooleanExpression);
        }

        /// <summary>
        /// Returns true if DSWorkflowBooleanExpression instances are equal
        /// </summary>
        /// <param name="other">Instance of DSWorkflowBooleanExpression to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DSWorkflowBooleanExpression other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Expressions == other.Expressions ||
                    this.Expressions != null &&
                    this.Expressions.SequenceEqual(other.Expressions)
                ) && 
                (
                    this.LogicalOperator == other.LogicalOperator ||
                    this.LogicalOperator != null &&
                    this.LogicalOperator.Equals(other.LogicalOperator)
                ) && 
                (
                    this.Type == other.Type ||
                    this.Type != null &&
                    this.Type.Equals(other.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Expressions != null)
                    hash = hash * 59 + this.Expressions.GetHashCode();
                if (this.LogicalOperator != null)
                    hash = hash * 59 + this.LogicalOperator.GetHashCode();
                if (this.Type != null)
                    hash = hash * 59 + this.Type.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
