/* 
 * Maestro API
 *
 * Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Maestro.Model
{
    /// <summary>
    /// DS Workflow Variable from a Participant
    /// </summary>
    [DataContract]
    public partial class DSWorkflowVariableFromParticipant :  IEquatable<DSWorkflowVariableFromParticipant>, IValidatableObject
    {
        public DSWorkflowVariableFromParticipant()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [DataMember(Name="key", EmitDefaultValue=false)]
        public ParticipantKeys? Key { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DSWorkflowVariableFromParticipant" /> class.
        /// </summary>
        /// <param name="Key">Key (required).</param>
        /// <param name="ParticipantId">ParticipantId (required).</param>
        /// <param name="Source">Source (required).</param>
        public DSWorkflowVariableFromParticipant(ParticipantKeys? Key = default(ParticipantKeys?), string ParticipantId = default(string), DSWorkflowVariableSourceTypesParticipant Source = default(DSWorkflowVariableSourceTypesParticipant))
        {
            // to ensure "Key" is required (not null)
            if (Key == null)
            {
                throw new InvalidDataException("Key is a required property for DSWorkflowVariableFromParticipant and cannot be null");
            }
            else
            {
                this.Key = Key;
            }
            // to ensure "ParticipantId" is required (not null)
            if (ParticipantId == null)
            {
                throw new InvalidDataException("ParticipantId is a required property for DSWorkflowVariableFromParticipant and cannot be null");
            }
            else
            {
                this.ParticipantId = ParticipantId;
            }
            // to ensure "Source" is required (not null)
            if (Source == null)
            {
                throw new InvalidDataException("Source is a required property for DSWorkflowVariableFromParticipant and cannot be null");
            }
            else
            {
                this.Source = Source;
            }
        }
        
        /// <summary>
        /// Gets or Sets ParticipantId
        /// </summary>
        [DataMember(Name="participantId", EmitDefaultValue=false)]
        public string ParticipantId { get; set; }
        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [DataMember(Name="source", EmitDefaultValue=false)]
        public DSWorkflowVariableSourceTypesParticipant Source { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DSWorkflowVariableFromParticipant {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  ParticipantId: ").Append(ParticipantId).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as DSWorkflowVariableFromParticipant);
        }

        /// <summary>
        /// Returns true if DSWorkflowVariableFromParticipant instances are equal
        /// </summary>
        /// <param name="other">Instance of DSWorkflowVariableFromParticipant to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DSWorkflowVariableFromParticipant other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Key == other.Key ||
                    this.Key != null &&
                    this.Key.Equals(other.Key)
                ) && 
                (
                    this.ParticipantId == other.ParticipantId ||
                    this.ParticipantId != null &&
                    this.ParticipantId.Equals(other.ParticipantId)
                ) && 
                (
                    this.Source == other.Source ||
                    this.Source != null &&
                    this.Source.Equals(other.Source)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Key != null)
                    hash = hash * 59 + this.Key.GetHashCode();
                if (this.ParticipantId != null)
                    hash = hash * 59 + this.ParticipantId.GetHashCode();
                if (this.Source != null)
                    hash = hash * 59 + this.Source.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
