/* 
 * Maestro API
 *
 * Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Maestro.Model
{
    /// <summary>
    /// Internal Error Codes
    /// </summary>
    /// <value>Internal Error Codes</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ErrorCodes
    {
        
        /// <summary>
        /// Enum _10001 for value: ERR_10001
        /// </summary>
        [EnumMember(Value = "ERR_10001")]
        _10001 = 1,
        
        /// <summary>
        /// Enum _10002 for value: ERR_10002
        /// </summary>
        [EnumMember(Value = "ERR_10002")]
        _10002 = 2,
        
        /// <summary>
        /// Enum _10003 for value: ERR_10003
        /// </summary>
        [EnumMember(Value = "ERR_10003")]
        _10003 = 3,
        
        /// <summary>
        /// Enum _10004 for value: ERR_10004
        /// </summary>
        [EnumMember(Value = "ERR_10004")]
        _10004 = 4,
        
        /// <summary>
        /// Enum _10005 for value: ERR_10005
        /// </summary>
        [EnumMember(Value = "ERR_10005")]
        _10005 = 5,
        
        /// <summary>
        /// Enum _10006 for value: ERR_10006
        /// </summary>
        [EnumMember(Value = "ERR_10006")]
        _10006 = 6,
        
        /// <summary>
        /// Enum _10007 for value: ERR_10007
        /// </summary>
        [EnumMember(Value = "ERR_10007")]
        _10007 = 7,
        
        /// <summary>
        /// Enum _10008 for value: ERR_10008
        /// </summary>
        [EnumMember(Value = "ERR_10008")]
        _10008 = 8,
        
        /// <summary>
        /// Enum _10009 for value: ERR_10009
        /// </summary>
        [EnumMember(Value = "ERR_10009")]
        _10009 = 9,
        
        /// <summary>
        /// Enum _10101 for value: ERR_10101
        /// </summary>
        [EnumMember(Value = "ERR_10101")]
        _10101 = 10,
        
        /// <summary>
        /// Enum _10201 for value: ERR_10201
        /// </summary>
        [EnumMember(Value = "ERR_10201")]
        _10201 = 11,
        
        /// <summary>
        /// Enum _10202 for value: ERR_10202
        /// </summary>
        [EnumMember(Value = "ERR_10202")]
        _10202 = 12,
        
        /// <summary>
        /// Enum _10301 for value: ERR_10301
        /// </summary>
        [EnumMember(Value = "ERR_10301")]
        _10301 = 13,
        
        /// <summary>
        /// Enum _10302 for value: ERR_10302
        /// </summary>
        [EnumMember(Value = "ERR_10302")]
        _10302 = 14,
        
        /// <summary>
        /// Enum _10401 for value: ERR_10401
        /// </summary>
        [EnumMember(Value = "ERR_10401")]
        _10401 = 15,
        
        /// <summary>
        /// Enum _10801 for value: ERR_10801
        /// </summary>
        [EnumMember(Value = "ERR_10801")]
        _10801 = 16,
        
        /// <summary>
        /// Enum _10802 for value: ERR_10802
        /// </summary>
        [EnumMember(Value = "ERR_10802")]
        _10802 = 17,
        
        /// <summary>
        /// Enum _10999 for value: ERR_10999
        /// </summary>
        [EnumMember(Value = "ERR_10999")]
        _10999 = 18
    }

}
