/* 
 * Maestro API
 *
 * Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Maestro.Model
{
    /// <summary>
    /// GetConfigurationInstancesResponse
    /// </summary>
    [DataContract]
    public partial class GetConfigurationInstancesResponse :  IEquatable<GetConfigurationInstancesResponse>, IValidatableObject
    {
        public GetConfigurationInstancesResponse()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GetConfigurationInstancesResponse" /> class.
        /// </summary>
        /// <param name="ConfigInstances">ConfigInstances.</param>
        /// <param name="Count">Count.</param>
        /// <param name="WorkflowDefinitionId">WorkflowDefinitionId.</param>
        public GetConfigurationInstancesResponse(List<GetConfigurationInstancesResponseConfigInstances> ConfigInstances = default(List<GetConfigurationInstancesResponseConfigInstances>), decimal? Count = default(decimal?), string WorkflowDefinitionId = default(string))
        {
            this.ConfigInstances = ConfigInstances;
            this.Count = Count;
            this.WorkflowDefinitionId = WorkflowDefinitionId;
        }
        
        /// <summary>
        /// Gets or Sets ConfigInstances
        /// </summary>
        [DataMember(Name="configInstances", EmitDefaultValue=false)]
        public List<GetConfigurationInstancesResponseConfigInstances> ConfigInstances { get; set; }
        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [DataMember(Name="count", EmitDefaultValue=false)]
        public decimal? Count { get; set; }
        /// <summary>
        /// Gets or Sets WorkflowDefinitionId
        /// </summary>
        [DataMember(Name="workflowDefinitionId", EmitDefaultValue=false)]
        public string WorkflowDefinitionId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetConfigurationInstancesResponse {\n");
            sb.Append("  ConfigInstances: ").Append(ConfigInstances).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  WorkflowDefinitionId: ").Append(WorkflowDefinitionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as GetConfigurationInstancesResponse);
        }

        /// <summary>
        /// Returns true if GetConfigurationInstancesResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of GetConfigurationInstancesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetConfigurationInstancesResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ConfigInstances == other.ConfigInstances ||
                    this.ConfigInstances != null &&
                    this.ConfigInstances.SequenceEqual(other.ConfigInstances)
                ) && 
                (
                    this.Count == other.Count ||
                    this.Count != null &&
                    this.Count.Equals(other.Count)
                ) && 
                (
                    this.WorkflowDefinitionId == other.WorkflowDefinitionId ||
                    this.WorkflowDefinitionId != null &&
                    this.WorkflowDefinitionId.Equals(other.WorkflowDefinitionId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ConfigInstances != null)
                    hash = hash * 59 + this.ConfigInstances.GetHashCode();
                if (this.Count != null)
                    hash = hash * 59 + this.Count.GetHashCode();
                if (this.WorkflowDefinitionId != null)
                    hash = hash * 59 + this.WorkflowDefinitionId.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
