/* 
 * Maestro API
 *
 * Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Maestro.Model
{
    /// <summary>
    /// The progress information for a workflow instance
    /// </summary>
    [DataContract]
    public partial class ProgressInstance :  IEquatable<ProgressInstance>, IValidatableObject
    {
        public ProgressInstance()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProgressInstance" /> class.
        /// </summary>
        /// <param name="CompletedSteps">The number of completed steps for this workflow instance.</param>
        /// <param name="CurrentCompletedStepName">The last completed step name.</param>
        /// <param name="TotalSteps">The total number of steps for this workflow instance.</param>
        public ProgressInstance(decimal? CompletedSteps = default(decimal?), string CurrentCompletedStepName = default(string), decimal? TotalSteps = default(decimal?))
        {
            this.CompletedSteps = CompletedSteps;
            this.CurrentCompletedStepName = CurrentCompletedStepName;
            this.TotalSteps = TotalSteps;
        }
        
        /// <summary>
        /// The number of completed steps for this workflow instance
        /// </summary>
        /// <value>The number of completed steps for this workflow instance</value>
        [DataMember(Name="completedSteps", EmitDefaultValue=false)]
        public decimal? CompletedSteps { get; set; }
        /// <summary>
        /// The last completed step name
        /// </summary>
        /// <value>The last completed step name</value>
        [DataMember(Name="currentCompletedStepName", EmitDefaultValue=false)]
        public string CurrentCompletedStepName { get; set; }
        /// <summary>
        /// The total number of steps for this workflow instance
        /// </summary>
        /// <value>The total number of steps for this workflow instance</value>
        [DataMember(Name="totalSteps", EmitDefaultValue=false)]
        public decimal? TotalSteps { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProgressInstance {\n");
            sb.Append("  CompletedSteps: ").Append(CompletedSteps).Append("\n");
            sb.Append("  CurrentCompletedStepName: ").Append(CurrentCompletedStepName).Append("\n");
            sb.Append("  TotalSteps: ").Append(TotalSteps).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ProgressInstance);
        }

        /// <summary>
        /// Returns true if ProgressInstance instances are equal
        /// </summary>
        /// <param name="other">Instance of ProgressInstance to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProgressInstance other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.CompletedSteps == other.CompletedSteps ||
                    this.CompletedSteps != null &&
                    this.CompletedSteps.Equals(other.CompletedSteps)
                ) && 
                (
                    this.CurrentCompletedStepName == other.CurrentCompletedStepName ||
                    this.CurrentCompletedStepName != null &&
                    this.CurrentCompletedStepName.Equals(other.CurrentCompletedStepName)
                ) && 
                (
                    this.TotalSteps == other.TotalSteps ||
                    this.TotalSteps != null &&
                    this.TotalSteps.Equals(other.TotalSteps)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CompletedSteps != null)
                    hash = hash * 59 + this.CompletedSteps.GetHashCode();
                if (this.CurrentCompletedStepName != null)
                    hash = hash * 59 + this.CurrentCompletedStepName.GetHashCode();
                if (this.TotalSteps != null)
                    hash = hash * 59 + this.TotalSteps.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
