/* 
 * Maestro API
 *
 * Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Maestro.Model
{
    /// <summary>
    /// Workflow Definition Metadata Status
    /// </summary>
    /// <value>Workflow Definition Metadata Status</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum WorkflowMetadataStatus
    {
        
        /// <summary>
        /// Enum Active for value: active
        /// </summary>
        [EnumMember(Value = "active")]
        Active = 1,
        
        /// <summary>
        /// Enum Inactive for value: inactive
        /// </summary>
        [EnumMember(Value = "inactive")]
        Inactive = 2,
        
        /// <summary>
        /// Enum Publishing for value: publishing
        /// </summary>
        [EnumMember(Value = "publishing")]
        Publishing = 3,
        
        /// <summary>
        /// Enum Unpublishing for value: unpublishing
        /// </summary>
        [EnumMember(Value = "unpublishing")]
        Unpublishing = 4,
        
        /// <summary>
        /// Enum Archived for value: archived
        /// </summary>
        [EnumMember(Value = "archived")]
        Archived = 5,
        
        /// <summary>
        /// Enum Archiving for value: archiving
        /// </summary>
        [EnumMember(Value = "archiving")]
        Archiving = 6
    }

}
